# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Prajjwal Bhandari
tagline:          ''
description:      'Student. Coder. Caffiene Addict.'
url:              http://pbhandari.ca
baseurl:          /

author:
  name:           'Prajjwal Bhandari'
  url:            http://pbhandari.ca
  email:          pbhandari@pbhandari.ca
  github:         http://github.com/pbhandari
  twitter:        https://twitter.com/prajjwal_b
  key:            http://p80.pool.sks-keyservers.net/pks/lookup?op=vindex&search=0x438F5F1D67D55E74&fingerprint=on

paginate:         5

# Custom vars
