# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Prajjwal Bhandari
tagline:          ''
description:      'Student. Coder. Caffiene Addict.'
url:              http://pbhandari.ca
baseurl:          /

author:
  name:           'Prajjwal Bhandari'
  url:            http://pbhandari.ca
  email:          pbhandari@pbhandari.ca
  github:         https://github.com/pbhandari
  keybase:        https://keybase.io/pbhandari
  twitter:        https://twitter.com/_pbhandari
  key:            https://pgp.mit.edu/pks/lookup?op=vindex&search=0x438F5F1D67D55E74&fingerprint=on

kramdown:
    use_coderay: true
    coderay:
        coderay_line_numbers: nil

paginate:         25

# Custom vars
