# Dependencies
markdown:         kramdown
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Prajjwal Bhandari
tagline:          ''
description:      'Student. Coder. Caffiene Addict.'
url:              http://pbhandari.ca
baseurl:          /

author:
  name:           'Prajjwal Bhandari'
  url:            http://pbhandari.ca
  github:         http://github.com/pbhandari
  twitter:        https://twitter.com/prajjwal_b
  key:

paginate:         5

# Custom vars
version:          2
